### ISSUE TITLE
Autoconvert old notebooks to latest

### ISSUE THREAD

**Issue by rgbkrk** [nteract/notebook-preview#11]
To truly make this a drop-in component, we should upgrade `v2 -> v4`, `v3 -> v4`. `commutable` has helpers for this, we need to apply them.

**Comment by jdfreder** [comment]
Commutable has 2->4?  I thought it only had 3->4

**Comment by rgbkrk** [comment]
Yup, @captainsafia added v2 -> v3.

**Comment by jdfreder** [comment]
Sweet!

**Comment by captainsafia** [comment]
`commutable` also has v2 -> v4. The upgrade function runs all the upgraders between two versions. So `upgrade(nb, 2, 4)` would upgraded v2 to v3 then take that notebook and upgrade it from v3 to v4.

[Here](https://github.com/nteract/commutable/blob/master/test/convert_spec.js#L27) is a test for this.

**Comment by rgbkrk** [comment]
Closing since we have this in the `@nteract/*` namespace now.
