### ISSUE TITLE
Rendering Performance Issues

### ISSUE THREAD

**Issue by tlyon3** [nteract/notebook-preview#20]
I've noticed some rendering performance issues with large files and it seems to be bottlenecking with CodeMirror and syntax highlighting.

@rgbkrk open a new issue in the nteract repo a few days ago discussing improving the usage of CodeMirror (https://github.com/nteract/nteract/issues/1977). 

One thing we might try is switching to another library that only does highlighting (like Prism.js) for syntax highlighting instead of CodeMirror.

A few months ago, the GitLab team was working on their rendering portion of the project. @sglyon suggested using the notebook-preview component and they liked what they saw. However, because they use Vue.js instead of React, they "ported" this to a Vue.js component. In the port, they decided to use Prism.js instead of CodeMirror for syntax highlighting and haven't had any performance issues.

This is just a suggestion. If you have a good reason for sticking with CodeMirror, I'd understand.

**Comment by rgbkrk** [comment]
I think using prism for the static notebook view is just fine. The reason we used codemirror here is because the live app uses codemirror and we already wrote a bunch of the code and styling for it. I'd welcome a change to using prism (or even switching to codemirrors static view mode). On commuter it's worth noting how we do it -- we render the code as text areas server side then switch to codemirror once the components are loaded.

**Comment by tlyon3** [comment]
Considering this is a "lightweight" notebook preview component, what other functionality is needed from CodeMirror other than static viewing?

**Comment by rgbkrk** [comment]
I'm totally in favor of switching it to prism. I don't personally have cycles to switch that over anytime soon, though I'm happy to merge it in. Probably worth noting you'll want the version in https://github.com/nteract/nteract/tree/master/packages/notebook-preview

**Comment by rgbkrk** [comment]
Alright, I've made an initial attempt at refactoring some of our cells and built-in styles. As part of it I went ahead and swapped CodeMirror out for a syntax highlighter that plugs in well with React (it forms an AST then applies classes to elements inside a pre block).

Demo: https://next-gen-nteract-components-uwslmwzqmi.now.sh
Repo: https://github.com/rgbkrk/next-gen-nteract-components

**Comment by rgbkrk** [comment]
Closing since we've been shipping this as part of `@nteract/notebook-preview`.
